[package]
name = "spotty"
version = "1.1.0"
edition = "2024"
authors = ["Vo Quoc Linh", "night0"]
description = "A modern Terminal User Interface for Spotify"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29"

rspotify = { version = "0.16", features = ["client-reqwest", "env-file", "cli"] }
librespot-core = "0.8.0"
librespot-playback = { version = "0.8.0", features = ["rodio-backend"] }
librespot-connect = "0.8.0"
librespot-metadata = "0.8.0"

tokio = { version = "1.51", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
anyhow = "1.0"
dirs = "6.0.0"
rand = "0.10.1"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }

[[bin]]
path = "src/main.rs"
name = "spotty"
bench = false
